name: clima
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.7
  geolocator: ^14.0.2
  http: ^1.5.0
  flutter_spinkit: ^5.2.2 # loading indicators animated
  flutter_dotenv: ^5.1.0  # secret key in .env



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
    - assets/.env

  fonts:
    - family: Spartan MB
      fonts:
        - asset: fonts/SpartanMB-Black.otf
          weight: 900